"""SCOVA-CF: governed population-counterfactual mean estimation."""

from .declaration import (
    AnalysisMode,
    ClaimClass,
    DeclarationAmendment,
    EstimatedAssignment,
    KnownAssignment,
    SCOVACFDeclaration,
    SupportPolicy,
)
from .applicability import (
    ApplicabilityAssessment,
    ApplicabilityClassification,
    ApplicabilityMatrix,
    assess_observational_applicability,
    observational_applicability_matrix,
)
from .estimator import SCOVACF, SCOVACFNuisancePredictions
from .result import (
    CFDesignLock,
    SCOVACFContrastEstimate,
    SCOVACFInferenceResult,
    SCOVACFOmnibusResult,
    SCOVACFResult,
    SeedStabilityResult,
)
from .status import QualificationStatus, SCOVACFRefusal, SCOVACFStatus, SupportStatus
from .scope_governance import (
    QUALIFICATION_REQUIRED_DECISION_IDS,
    ScopeDecision,
    applicability_matrix_checksum,
    build_qualification_manifest,
    scope_decision_registry,
    validate_manifest,
    validate_record,
    validate_registry,
)
from .studies import (
    ARTIFACT_SCHEMA_VERSION,
    METHODS_STUDY_ID,
    QUALIFICATION_PROTOCOL_ID,
    StudyProgram,
    assert_program_artifact,
    factorial_cells,
    methods_design,
    qualification_cells,
    qualification_design,
)
from .validation import (
    CFSupportProfile,
    CFValidationProtocol,
    SeedPartition,
    canonical_checksum,
)

__all__ = [
    "AnalysisMode",
    "ARTIFACT_SCHEMA_VERSION",
    "ApplicabilityAssessment",
    "ApplicabilityClassification",
    "ApplicabilityMatrix",
    "CFDesignLock",
    "CFSupportProfile",
    "CFValidationProtocol",
    "ClaimClass",
    "DeclarationAmendment",
    "EstimatedAssignment",
    "KnownAssignment",
    "METHODS_STUDY_ID",
    "QUALIFICATION_PROTOCOL_ID",
    "QualificationStatus",
    "QUALIFICATION_REQUIRED_DECISION_IDS",
    "SCOVACF",
    "SCOVACFContrastEstimate",
    "SCOVACFDeclaration",
    "SCOVACFInferenceResult",
    "SCOVACFNuisancePredictions",
    "SCOVACFOmnibusResult",
    "SCOVACFRefusal",
    "SCOVACFResult",
    "SCOVACFStatus",
    "SeedStabilityResult",
    "ScopeDecision",
    "SeedPartition",
    "SupportPolicy",
    "SupportStatus",
    "StudyProgram",
    "assert_program_artifact",
    "canonical_checksum",
    "assess_observational_applicability",
    "applicability_matrix_checksum",
    "build_qualification_manifest",
    "factorial_cells",
    "methods_design",
    "observational_applicability_matrix",
    "qualification_cells",
    "qualification_design",
    "scope_decision_registry",
    "validate_manifest",
    "validate_record",
    "validate_registry",
]
